### ISSUE TITLE
Two-Step Verification

### ISSUE THREAD

**Issue by kionlife** [thebrumby/HotWalletClaimer#5]
Hi. Please add support for Two-Step Verification

**Comment by thebrumby** [comment]
Hi Kionlife,

I never thought of that, let me look this weekend at what's involved in implementing that.

**Comment by kionlife** [comment]
Thank you very much. I spent half the night setting it up and only then, after turning on debug mode, did I see that it was asking for the password to my account 😅

**Comment by thebrumby** [comment]
Hey Kionlife,

I've implemented the 2FA check in the script! After logging in—whether by scanning the QR code or entering your registered phone number and OTP—the script will now check for the presence of a 2FA password box for 5 seconds.

If a password box is detected, it will prompt you to enter your password, which it then securely passes to Telegram. I've tested it in various scenarios, including accounts with and without 2FA enabled, and everything seems to be working smoothly.

Could you please download `claim.py` from version 1.4.1 and let me know how it works for you? Your feedback would be greatly appreciated!

**Comment by Sergey26Tarasenko** [comment]
> Thank you very much. I spent half the night setting it up and only then, after turning on debug mode, did I see that it was asking for the password to my account 😅

It's good that there is a debug mode, I also saw that I need to enter a 2FA code.

**Comment by thebrumby** [comment]
I'm very pleased to hear you got everything sorted, Sergey. I never thought to add that, as I don't use it myself. Maybe I should start!

**Comment by Sergey26Tarasenko** [comment]
@thebrumby Now we need to disable 2FA on telegram account and wait new version script?

screenshots take at debugIsOn = true
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/f48aa8f9-52f4-42ac-ad6b-e6cd80ddd4d6)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/fa3fb14f-be58-4483-b4e8-390eb3043a2d)

**Comment by thebrumby** [comment]
Hey Sergey,

It seems things didn't quite work out as I had hoped! I tested the code several times yesterday before rolling it out, and it worked perfectly each time.

I've just pushed today's changes up as version 1.4.2, which I hope will resolve your issues. Again, I tested it in various scenarios (QR code/OTP, with and without 2FA), and all are working as expected for me.

Please let me know how you get on.

**Comment by Sergey26Tarasenko** [comment]
Hello! I still see problems with enable 2FA on telegram account. I disable all active python task, cleared pm2 list and clear bakup folder from project. After I updated to 1.4.2 and run to work, but I still see problem...
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/64f276e3-7395-4998-b90b-3414aac7c913)

**Comment by Sergey26Tarasenko** [comment]
I tried work without PM2, just create new session and enter Y for continue script. I see that first step 2FA has success result, but in future has probrem with it

![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/211e68a5-b783-488d-b73a-b2c7a8ec24a9)

**Comment by thebrumby** [comment]
Hi Serget,

Is the last image from PM2? If so, it appears you appear to be starting it incorrectly. The session name you used in the python3 claim.py command must also be included in the PM2 command when starting the script. 

<img width="637" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/783b7afd-4b68-4fb2-b6a8-88f5b725f3db">

In this example, our session name/folder name is "2", you would start PM2 like this:

```bash
pm2 start claim.py --name myFirstPMWallet -- 2
```

While the name specified after --name can be any name of your choosing, it's crucial that -- 2 matches the folder name. In PM2, you should then see the following output:

<img width="715" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/ca89c747-8dc6-4ef5-8b88-61f4ec55e48a">

**Comment by Sergey26Tarasenko** [comment]
> Hi Sergey,
> 
> Is the last image from PM2? If so, it appears you may be starting it incorrectly. The session name you used in the python3 claim.py command must also be included in the PM2 command when starting the script.
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/29182343/322264879-783b7afd-4b68-4fb2-b6a8-88f5b725f3db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTcwMzEsIm5iZiI6MTcxMzA5NjczMSwicGF0aCI6Ii8yOTE4MjM0My8zMjIyNjQ4NzktNzgzYjdhZmQtNGI2OC00ZmIyLWI2YTgtODhmNWI3MjVmM2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDEyMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZmUwOWM4NzE4MmRmZDAzNGMyZTAyNjc1ZGIzMDI4OGViZmU0NGUyMjk0MDg3ZjU1MmE0NzFlZmI0MWU5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6z6uga3mUnrD2dEk1NOWNw-H_4b-uKdBbkE6_4TM54">
> In this example, our session name/folder name is "2", so you would start PM2 like this:
> 
> ```shell
> pm2 start claim.py --name myFirstPMWallet -- 2
> ```
> 
> While the name specified after --name can be any name of your choosing, it's crucial that -- 2 matches the folder name of the saved session. In PM2, you should then see the following output:
> 
> <img alt="image" width="715" src="https://private-user-images.githubusercontent.com/29182343/322266498-ca89c747-8dc6-4ef5-8b88-61f4ec55e48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTcwMzEsIm5iZiI6MTcxMzA5NjczMSwicGF0aCI6Ii8yOTE4MjM0My8zMjIyNjY0OTgtY2E4OWM3NDctOGRjNi00ZWY1LThiODgtNjFmNGVjNTVlNDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDEyMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiM2I4MGJmMWZmNTI5YTY1NjE5MTQ2NzBjNjBkYjdlYzkxN2NhZDU3Njk0MmRhZWY3OGZjMjliZmI2ODZhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RydFCDEVVe-d0mObt-XMiOO1pWiwJWYh_urIVsELhS0">

I think I have the right path name 
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/1b3de788-a36d-4b83-bae9-f6cf6f8663d2)

**Comment by Sergey26Tarasenko** [comment]
Okay, I will try to use the simple naming of the session. Only digits.

**Comment by thebrumby** [comment]
![image](https://private-user-images.githubusercontent.com/11050608/322272069-1b3de788-a36d-4b83-bae9-f6cf6f8663d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTk2MzAsIm5iZiI6MTcxMzA5OTMzMCwicGF0aCI6Ii8xMTA1MDYwOC8zMjIyNzIwNjktMWIzZGU3ODgtYTM2ZC00YjgzLWJhZTktZjZjZjZmODY2M2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDEyNTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZjFmOTZlYjI3NzYxNTA5NTU4MGY4NjNmN2NmZTUxNjc5YWZlNzI0OTYxZDUzYmI5Y2UxMWUyNGQ5YjYwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkPFkJmsJqCR4xrSCr5YI27VS5Q2rjHSeDFbiplMc6I)

In this screenshot, the errors at the end indicate that you are not successfully logged in. The message at the top reveals that it can't find the chat box to send commands. It attempted to restore from a backup, but the backup is also corrupted. Consequently, at the bottom, it fails to retrieve the wait timer.

I recommend stopping the PM2 process for now. Run python3 claim.py again, update the settings, and make sure to enable the last option to force a new login. Then, go through the setup process again for oSession5. At the end of the setup, choose 'n' to exit and resume later with PM2. Afterward, restart the process in PM2.

**Comment by Sergey26Tarasenko** [comment]
>  ![image](https://private-user-images.githubusercontent.com/11050608/322272069-1b3de788-a36d-4b83-bae9-f6cf6f8663d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTk2MzAsIm5iZiI6MTcxMzA5OTMzMCwicGF0aCI6Ii8xMTA1MDYwOC8zMjIyNzIwNjktMWIzZGU3ODgtYTM2ZC00YjgzLWJhZTktZjZjZjZmODY2M2QyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDEyNTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZjFmOTZlYjI3NzYxNTA5NTU4MGY4NjNmN2NmZTUxNjc5YWZlNzI0OTYxZDUzYmI5Y2UxMWUyNGQ5YjYwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkPFkJmsJqCR4xrSCr5YI27VS5Q2rjHSeDFbiplMc6I)
> 
> In this screenshot, the errors at the end indicate that you are not successfully logged in. The message at the top reveals that it can't find the chat box to send commands. It attempted to restore from a backup, but the backup is also corrupted. Consequently, at the bottom, it fails to retrieve the wait timer.
> 
> I recommend stopping the PM2 process for now. Run python3 claim.py again, update the settings, and make sure to enable the last option to force a new login. Then, go through the setup process again for oSession5. At the end of the setup, choose 'n' to exit and resume later with PM2. Afterward, restart the process in PM2.

What do you think. To begin with, maybe I should do it without PM2 and make sure that it works correctly? I have problems working without using PM2.

**Comment by thebrumby** [comment]
Absolutely my friend :)

"Before using PM2 to manage your wallet sessions, you should open the script with python3 claim.py and set up each wallet. After following the process to sign into Telegram and enter your seed phrase, you will be prompted if you want to exit before being handed over to the claim function. You can select 'n' to exit the script and resume the session with PM2 as outlined below."

Will we add an option this afternoon so it will offer to configure PM2 for you.

**Comment by Sergey26Tarasenko** [comment]
> Absolutely my friend :)
> 
> "Before using PM2 to manage your wallet sessions, you should open the script with python3 claim.py and set up each wallet. After following the process to sign into Telegram and enter your seed phrase, you will be prompted if you want to exit before being handed over to the claim function. You can select 'n' to exit the script and resume the session with PM2 as outlined below."
> 
> Will we add an option this afternoon so it will offer to configure PM2 for you.

I still see problems ;( I see more screenshots of debug mode and I see that problem with 2FA. Only screenshots with monkey.

1. I don't use unique naming. Just empty and take next free digits naming (1)
2. I don't use PM2. Only run command 'python3 claim.py'. Without naming
3. I have success login by QR code, success 2FA at first step!

![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/684f69b9-3e03-4aa2-a7e0-a6e08cbf9983)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/47a4f955-3b6d-443d-8041-7f40ccbea1fd)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/19b4cafe-39ff-4ce3-a642-87385f2bd907)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/ddf425ca-dcba-4a88-b0d0-d544bc646a61)

**Comment by Sergey26Tarasenko** [comment]
Any ideas?

**Comment by thebrumby** [comment]
I added the option that it will set PM2 up for you now :) If you stop anything active in PM2 and update to the latest script :)

**Comment by Sergey26Tarasenko** [comment]
> I added the option that it will set PM2 up for you now :) If you stop anything active in PM2 and update to the latest script :)

Sorry, I don't understand you). Maybe it's worth figuring out why the script doesn't work without using PM2? I've used two options and I always see the same thing. The problem with 2FA. The screenshots show the same window with a monkey. Recent screenshots without PM2. Maybe it's worth dealing with the script first?

**Comment by Sergey26Tarasenko** [comment]
@thebrumby I tried update project to lastest commit https://github.com/thebrumby/HotWalletClaimer/commit/c7b611ad4e69ca371f4147df051f49321ad13e75

and kill all project chrome, chromdriver, python, remove severals folders ... bakups, selenium and tried to run python3 claim.py. 
I still see old problem ;(

**Comment by Sergey26Tarasenko** [comment]
@thebrumby I tried work by new option 'a' for pm2. I still see problem with 2FA on the next steps... attach all logs

![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/a51639ce-8348-4179-8b11-a96452dd5471)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/11050608/adf0fd3f-7d73-46da-b83c-31fcd658f63d)

**Comment by thebrumby** [comment]
Well, to clarify, the login with the seed phrase occurs at https://tgapp.herewallet.app/ (the game provider's site), so it's separate from the Telegram login process. Reviewing your screenshots more closely, it appears you never successfully log into Telegram, and your 2FA doesn't complete. This is puzzling as I've tested this on Ubuntu 22.04 and 20.04, on VPSs in Germany, the UK, and the USA, with accounts both with and without 2FA, and I haven't encountered this issue.

Are you using a VPS or a local machine? The quickest solution might be to temporarily disable 2FA to log into your accounts. Once logged in, you should remain logged in and can then re-enable 2FA. If that doesn't work, another option is to try using a cloud VPS running Ubuntu 22, which might offer a more consistent environment for running the script.

**Comment by Sergey26Tarasenko** [comment]
Local computer without proxy, VPN

**Comment by Sergey26Tarasenko** [comment]
> Well, to clarify, the login with the seed phrase occurs at https://tgapp.herewallet.app/ (the game provider's site), so it's separate from the Telegram login process. Reviewing your screenshots more closely, it appears you never successfully log into Telegram, and your 2FA doesn't complete. This is puzzling as I've tested this on Ubuntu 22.04 and 20.04, on VPSs in Germany, the UK, and the USA, with accounts both with and without 2FA, and I haven't encountered this issue.
> 
> Are you using a VPS or a local machine? The quickest solution might be to temporarily disable 2FA to log into your accounts. Once logged in, you should remain logged in and can then re-enable 2FA. If that doesn't work, another option is to try using a cloud VPS running Ubuntu 22, which might offer a more consistent environment for running the script.
> 

....it appears you never successfully log into Telegram, and your 2FA doesn't complete.....

yeah it's true! I saw a telegram chat and read about it. 

message from chat 

".......The code was entered correctly, but the correct password was not specified...."

**Comment by thebrumby** [comment]
Is it this message?

<img width="340" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/8af6db51-e34f-4c6c-bd2a-e46412497d03">

I got that when I forgot my 2FA (I couldn't remember what punctuation I used). I tried to remove it in Telegram, and it wouldn't let me, so I have to click recover by email and created a new password.

**Comment by Sergey26Tarasenko** [comment]
> Is it this message?
> 
> <img width="340" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/8af6db51-e34f-4c6c-bd2a-e46412497d03">
> 
> I got that when I forgot my 2FA (I couldn't remember what punctuation I used). I tried to remove it in Telegram, and it wouldn't let me, so I have to click recover by email and created a new password.

Sorry, I remember 2FA code and correct write this. If you open my screenshot, you can see text about this!

...Step 01g - 2FA passwork entered successfully...

After I see the screenshots from debug that script has access to telegram and work with near wallet app. 

I selected this text with green line for you!

Why do I have a problem after  Step 12? I see that latest correct step and after display error text

...We backed up the session data....

**Comment by Sergey26Tarasenko** [comment]
> Thank you very much. I spent half the night setting it up and only then, after turning on debug mode, did I see that it was asking for the password to my account 😅

Hello. Have you tried the new version of the script? it's okay?

**Comment by thebrumby** [comment]
Hi,

I have now updated version 1.4.4 to help with debugging:

Version 1.4.4 includes enhanced validation for users with 2FA enabled. The update introduces two crucial checks: the first verifies that Telegram has not reported the password as incorrect, and the second detects any other errors, such as a blank password field, indicating that the password may not have been transmitted properly. If you encounter errors, please enable debugging in the settings. This will capture screenshots that can assist in diagnosing potential issues.

![01h-Test QR code after session is resumed](https://github.com/thebrumby/HotWalletClaimer/assets/29182343/55589f3e-b926-46ff-b042-e52e0ab0bf30)

**Comment by Sergey26Tarasenko** [comment]
Thank you for your time! I have success result at enabled 2FA. I don't know what happend, but it's work!

**Comment by thebrumby** [comment]
Hey Sergey, I didn’t change any logic around 2FA, I only added the error checking, but so pleased it is working for you. Happy mining.
